# Generated by Django 6.1 on 2026-09-07 06:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('order', models.CharField(choices=[('pairwise_first', 'Design 1 then Design 2'), ('ranking_first', 'Design 2 then Design 1')], max_length=20)),
                ('is_demo', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('preferred_design', models.CharField(blank=True, max_length=20)),
                ('exit_answers', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('condition', models.CharField(choices=[('pairwise', 'Design 1: pairwise comparisons'), ('ranking', 'Design 2: ranking of ten')], max_length=20)),
                ('tasks_planned', models.PositiveIntegerField(default=0)),
                ('tasks_done', models.PositiveIntegerField(default=0)),
                ('holdout_planned', models.PositiveIntegerField(default=0)),
                ('holdout_done', models.PositiveIntegerField(default=0)),
                ('weights', models.JSONField(blank=True, default=list)),
                ('holdout_accuracy', models.FloatField(blank=True, null=True)),
                ('holdout_log_loss', models.FloatField(blank=True, null=True)),
                ('elicitation_seconds', models.FloatField(default=0)),
                ('ratings', models.JSONField(blank=True, default=dict)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='project4.participant')),
            ],
            options={
                'ordering': ['participant', 'index'],
                'unique_together': {('participant', 'index')},
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('elicitation', 'Elicitation'), ('holdout', 'Held out')], max_length=20)),
                ('position', models.PositiveIntegerField()),
                ('shown', models.JSONField(default=list)),
                ('order', models.JSONField(default=list)),
                ('seconds', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='project4.block')),
            ],
            options={
                'ordering': ['block', 'phase', 'position'],
                'unique_together': {('block', 'phase', 'position')},
            },
        ),
    ]
