# Generated by Django 6.1 on 2026-08-27 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('file', models.FileField(upload_to='project1/datasets/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('n_rows', models.PositiveIntegerField(default=0)),
                ('n_features', models.PositiveIntegerField(default=0)),
                ('target_name', models.CharField(blank=True, max_length=120)),
                ('feature_names', models.JSONField(blank=True, default=list)),
                ('dropped_columns', models.JSONField(blank=True, default=list)),
                ('detected_task', models.CharField(choices=[('classification', 'Classification'), ('regression', 'Regression')], default='classification', max_length=20)),
                ('detection_reason', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(max_length=40)),
                ('task_type', models.CharField(choices=[('classification', 'Classification'), ('regression', 'Regression')], max_length=20)),
                ('hyperparameter', models.CharField(max_length=60)),
                ('values', models.JSONField(default=list)),
                ('test_size', models.FloatField(default=0.25)),
                ('random_state', models.IntegerField(default=0)),
                ('stratified', models.BooleanField(default=True)),
                ('score_name', models.CharField(max_length=40)),
                ('results', models.JSONField(default=list)),
                ('best_value', models.CharField(blank=True, max_length=40)),
                ('best_score', models.FloatField(blank=True, null=True)),
                ('seconds', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='project1.dataset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
